const CellarActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  INCREMENT_ITEM_QUANTITY: "INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "DECREMENT_ITEM_QUANTITY",
  SET_CELLAR_ITEMS: "SET_CELLAR_ITEMS",
};

export default CellarActionTypes;
